### ISSUE TITLE
Failed to resolve component: vue-awesome-paginate

### ISSUE THREAD

**Issue by pelargir** [peshanghiwa/vue-awesome-paginate#23]
We're getting a warning in the logs running Nuxt 3:

```
[Vue warn]: Failed to resolve component: vue-awesome-paginate
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
```

The component works, but it would be nice to eliminate the warning to avoid the extra noise in the logs. Any ideas?

**Comment by peshanghiwa** [comment]
This really looks like you have not registered the component, or maybe you have registered it with a different name, can you please share a sandbox or the part of your codebase where you have registered your component?

**Comment by pelargir** [comment]
We followed your instructions for Nuxt and put this in the plugins folder:

```js
import VueAwesomePaginate from "vue-awesome-paginate";

import "vue-awesome-paginate/dist/style.css";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueAwesomePaginate);
});
```

**Comment by limingcan562** [comment]
> We're getting a warning in the logs running Nuxt 3:
> 
> ```
> [Vue warn]: Failed to resolve component: vue-awesome-paginate
> If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
> ```
> 
> The component works, but it would be nice to eliminate the warning to avoid the extra noise in the logs. Any ideas?

Hi, what is your version of `nuxt`, I have no problem using it on my side, my version is `3.13.0`

**Comment by pelargir** [comment]
We're running Nuxt 3.13, but I'm not seeing the warning any longer. It must have been a problem specific to my local system. Maybe my Node version? I haven't been able to nail it down but it's not happening now.
