### ISSUE TITLE
First and last page buttons visibility 

### ISSUE THREAD

**Issue by bozziche** [peshanghiwa/vue-awesome-paginate#3]
When the active page number equals the "`max-page-shown`" attribute's value, the first page button is hidden. The same behavior happens for the last page button when we reach the [total pages] - [max-page-shown] value.
Is this by design? Could it be changed with an attribute?

**Comment by peshanghiwa** [comment]
Thank you very much for this report, it was an issue and it's now fixed and released on version 1.0.5
