### ISSUE TITLE
Updating the current page prop value does not change the total pages

### ISSUE THREAD

**Issue by sjanneflinterman** [peshanghiwa/vue-awesome-paginate#4]
Like the title says, updating the current page prop programmatically does not change the current page in the vue-awesome-paginate component. To give some context as to where this is useful: I need to 'reset' the pagination back to 1 whenever I perform a filter or search action on my table with pagination.

**Comment by peshanghiwa** [comment]
Hello dear @sjanneflinterman 

Thank you very much for this really critical bug report, it's now fixed and published on NPM with latest version **1.1.0**.
I Have deprecated currentPage prop as i believe it's not really useful as it's not reactive and replaced it with Vue's default v-model prop and it makes more sense now.

The documentation is also updated you can check it now.

Best.

**Comment by CreaticDD** [comment]
Thank you!
