### ISSUE TITLE
Problem with Vite

### ISSUE THREAD

**Issue by rafnsteingrims** [peshanghiwa/vue-awesome-paginate#7]
I have a simple Vue.js project that I set up with Vite and when I install this package and try to build I get this error message:
```
[commonjs--resolver] Failed to resolve entry for package "vue-awesome-paginate". The package may have incorrect main/module/exports specified in its package.json.
```

Checked the vue-awesome-paginate folder in node_modules and the only files that were there were package.json, README.md, and LICENSE. No errors came up during installation.

**Comment by phatdangg** [comment]
Got the same problem on new version **1.1.45**
@rafnsteingrims I have tried downgrading to old version 1.1.4 and it's working as well

**Comment by cantkillemall** [comment]
I think this is just a question of building the package before updating NPM. The 'dist' folder is not there.

**Comment by peshanghiwa** [comment]
Dear @rafnsteingrims,
Thank you very much for reporting this issue, there was a problem in the build and the dist folder was missing, it's now fixed.
