### ISSUE TITLE
Allow to set CSS class for <li>

### ISSUE THREAD

**Issue by qzminski** [peshanghiwa/vue-awesome-paginate#8]
It should be possible to set CSS class for the `<li>` element.

**Comment by qzminski** [comment]
Sorry, why was this closed? I could provide a pull request if that helps 🙂

**Comment by peshanghiwa** [comment]
It's added and it will be available in the next release.

Thank you very much for the suggestion 🙏🏻

**Comment by qzminski** [comment]
Thank you for implementing this! 👍
